package gruz

type Lesson struct {
	Auditorium                string      `json:"auditorium"`
	AuditoriumAmount          int         `json:"auditoriumAmount"`
	AuditoriumGUID            string      `json:"auditoriumGUID"`
	AuditoriumOid             int         `json:"auditoriumOid"`
	Author                    string      `json:"author"`
	BeginLesson               string      `json:"beginLesson"`
	Building                  string      `json:"building"`
	BuildingGid               int         `json:"buildingGid"`
	BuildingOid               int         `json:"buildingOid"`
	ContentOfLoadOid          int         `json:"contentOfLoadOid"`
	ContentOfLoadUID          string      `json:"contentOfLoadUID"`
	ContentTableOfLessonsName string      `json:"contentTableOfLessonsName"`
	ContentTableOfLessonsOid  int         `json:"contentTableOfLessonsOid"`
	Createddate               string      `json:"createddate"`
	Date                      string      `json:"date"`
	DateOfNest                string      `json:"dateOfNest"`
	DayOfWeek                 int         `json:"dayOfWeek"`
	DayOfWeekString           string      `json:"dayOfWeekString"`
	DetailInfo                string      `json:"detailInfo"`
	Discipline                string      `json:"discipline"`
	DisciplineOid             int         `json:"disciplineOid"`
	Disciplineinplan          string      `json:"disciplineinplan"`
	Disciplinetypeload        int         `json:"disciplinetypeload"`
	Duration                  int         `json:"duration"`
	EndLesson                 string      `json:"endLesson"`
	Group                     string      `json:"group"`
	GroupGUID                 string      `json:"groupGUID"`
	GroupOid                  int         `json:"groupOid"`
	GroupUID                  string      `json:"groupUID"`
	GroupFacultyoid           int         `json:"group_facultyoid"`
	Hideincapacity            int         `json:"hideincapacity"`
	IsBan                     bool        `json:"isBan"`
	KindOfWork                string      `json:"kindOfWork"`
	KindOfWorkComplexity      int         `json:"kindOfWorkComplexity"`
	KindOfWorkOid             int         `json:"kindOfWorkOid"`
	KindOfWorkUid             string      `json:"kindOfWorkUid"`
	Lecturer                  string      `json:"lecturer"`
	LecturerCustomUID         interface{} `json:"lecturerCustomUID"`
	LecturerEmail             *string     `json:"lecturerEmail"`
	LecturerGUID              string      `json:"lecturerGUID"`
	LecturerOid               int         `json:"lecturerOid"`
	LecturerUID               string      `json:"lecturerUID"`
	LecturerPostOid           int         `json:"lecturer_post_oid"`
	LecturerRank              string      `json:"lecturer_rank"`
	LecturerTitle             string      `json:"lecturer_title"`
	LessonNumberEnd           int         `json:"lessonNumberEnd"`
	LessonNumberStart         int         `json:"lessonNumberStart"`
	LessonOid                 int         `json:"lessonOid"`
	ListOfLecturers           []struct {
		Lecturer          string      `json:"lecturer"`
		LecturerCustomUID interface{} `json:"lecturerCustomUID"`
		LecturerEmail     *string     `json:"lecturerEmail"`
		LecturerGUID      interface{} `json:"lecturerGUID"`
		LecturerOid       int         `json:"lecturerOid"`
		LecturerUID       string      `json:"lecturerUID"`
		LecturerPostOid   int         `json:"lecturer_post_oid"`
		LecturerRank      string      `json:"lecturer_rank"`
		LecturerTitle     string      `json:"lecturer_title"`
	} `json:"listOfLecturers"`
	Modifieddate       string      `json:"modifieddate"`
	Note               interface{} `json:"note"`
	NoteDescription    string      `json:"note_description"`
	Parentschedule     string      `json:"parentschedule"`
	Replaces           interface{} `json:"replaces"`
	Stream             interface{} `json:"stream"`
	StreamOid          int         `json:"streamOid"`
	StreamFacultyoid   int         `json:"stream_facultyoid"`
	SubGroup           interface{} `json:"subGroup"`
	SubGroupOid        int         `json:"subGroupOid"`
	SubgroupFacultyoid int         `json:"subgroup_facultyoid"`
	TableofLessonsName string      `json:"tableofLessonsName"`
	TableofLessonsOid  int         `json:"tableofLessonsOid"`
	Url1               *string     `json:"url1"`
	Url1Description    *string     `json:"url1_description"`
	Url2               *string     `json:"url2"`
	Url2Description    *string     `json:"url2_description"`
}

type MailInfo struct {
	Id    string `json:"id"`
	Uns   string `json:"uns"`
	Type  string `json:"type"`
	Email string `json:"email"`
	Fio   string `json:"fio"`
	Info  string `json:"info"`
}
